"""Phase 4 Final v2

Revision ID: ef2f71c7bfb5
Revises: 
Create Date: 2026-01-30 18:47:00.499168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2f71c7bfb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('start_line', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    # op.create_table('payments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('order_id', sa.Integer(), nullable=False),
    # sa.Column('amount', sa.Float(), nullable=False),
    # sa.Column('currency', sa.String(length=10), nullable=True),
    # sa.Column('provider', sa.String(length=50), nullable=True),
    # sa.Column('transaction_id', sa.String(length=255), nullable=True),
    # sa.Column('razorpay_order_id', sa.String(length=255), nullable=False),
    # sa.Column('status', sa.String(length=50), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('order_id')
    # )
    # op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('courier_name', sa.String(length=100), nullable=True),
    sa.Column('tracking_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    # op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    # op.alter_column('carts', 'created_at', ...) # Skipped existing updates
    # op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    # op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    # op.alter_column('carts', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(getdate())'))
    # op.alter_column('carts', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    # op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('orders', sa.Column('shipping_address_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('shipping_cost', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    # op.alter_column('orders', 'status',
    #            existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
    #            type_=sa.String(),
    #            existing_nullable=True,
    #            existing_server_default=sa.text("('pending')"))
    # op.alter_column('orders', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(getdate())'))
    # op.alter_column('orders', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_foreign_key(None, 'orders', 'addresses', ['shipping_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text("('pending')"))
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'shipping_cost')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.alter_column('carts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('carts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
