"""Add image_url to products

Revision ID: f4135b05f091
Revises: 007c2e49d411
Create Date: 2026-02-13 12:40:51.726925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4135b05f091'
down_revision = '007c2e49d411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('payments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('order_id', sa.Integer(), nullable=False),
    # sa.Column('amount', sa.Float(), nullable=False),
    # sa.Column('currency', sa.String(length=10), nullable=True),
    # sa.Column('provider', sa.String(length=50), nullable=True),
    # sa.Column('transaction_id', sa.String(length=255), nullable=True),
    # sa.Column('razorpay_order_id', sa.String(length=255), nullable=False),
    # sa.Column('status', sa.String(length=50), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('order_id')
    # )
    # op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    # op.alter_column('carts', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(getdate())'))
    # op.alter_column('carts', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    # op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    # op.alter_column('orders', 'status',
    #            existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
    #            type_=sa.String(),
    #            existing_nullable=True,
    #            existing_server_default=sa.text("('pending')"))
    # op.alter_column('orders', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(getdate())'))
    # op.alter_column('orders', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text("('pending')"))
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.alter_column('carts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('carts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
